import { Bai_Jamjuree, Mali } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css'; //add
import "./globals.css";

const baiJamjuree = Bai_Jamjuree({
  subsets: ['thai', 'latin'],
  weight: ['200', '300', '400', '500', '600', '700'],
  variable: '--font-bai-jamjuree',
})

const mali = Mali({
  subsets: ['thai', 'latin'],
  weight: ['200', '300', '400', '500', '600', '700'],
  variable: '--font-mali',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link 
          rel="stylesheet" 
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=home" 
        />
      </head>
      <body className={`${baiJamjuree.variable} ${mali.variable}`}>
        {children}
      </body>
    </html>
  );
}
